#Here we are building mongo and mongo-express containers through files instead command line. Files are convinent way to run commands, 
#Advantages of docker compose: Files contains commands in a more structured way. Additionally, we can manage to edit commands any time.  

version: "3.8"    #Can skip this attribute/option

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/